name: sentinel_mesh
description: Decentralized Safety Network
publish_to: 'none'

environment:
  sdk: '^3.11.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.30.0
  firebase_database: ^10.5.0
  firebase_auth: ^4.19.0
  
  # Location & Permissions
  geolocator: ^11.0.0
  permission_handler: ^11.3.0
  
  # Notifications & Camera
  flutter_local_notifications: ^17.1.0
  camera: ^0.10.5

  # UI & Utilities
  google_fonts: ^6.2.1
  url_launcher: ^6.2.6
  shared_preferences: ^2.2.3
  google_maps_flutter: ^2.14.2
  http: ^1.6.0
  google_generative_ai: ^0.4.7
  agora_rtc_engine: ^6.5.4
  flutter_polyline_points: ^3.1.0
  flutter_blue_plus: ^1.34.4
  flutter_background_service: ^5.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true